import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem> */}
        <body>{children}</body>
      {/* </ThemeProvider> */}
    </html>
  );
}
